name: Deploy NestJS app to EC2

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}

      - name: Package build folder
        run: |
          tar -czf app.tar.gz dist package.json package-lock.json

      - name: Upload tarball to EC2
        run: |
          scp -o StrictHostKeyChecking=no app.tar.gz ubuntu@${{ secrets.SERVER_HOST }}:/home/ubuntu/

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} <<'EOF'
            set -euo pipefail

            APP_DIR="/home/dinil-dev/system-storage/apps/machemaven-api"
            TAR="/home/ubuntu/app.tar.gz"
            SERVICE="machemaven-api"

            echo "[1/5] Stop service if running"
            sudo systemctl stop "$SERVICE" || true

            echo "[2/5] Prepare dir and clean old files"
            mkdir -p "$APP_DIR"
            find "$APP_DIR" -mindepth 1 -maxdepth 1 -exec rm -rf {} +

            echo "[3/5] Extract new build"
            tar -xzf "$TAR" -C "$APP_DIR"

            echo "[4/5] Install production deps"
            cd "$APP_DIR"
            npm ci --omit=dev

            echo "[5/5] Start service"
            sudo systemctl start "$SERVICE"
            sudo systemctl status "$SERVICE" --no-pager || true
          EOF
