name: Deploy NestJS app to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Package build folder
        run: |
          tar -czf app.tar.gz dist package.json package-lock.json

      - name: Upload tarball to EC2
        run: |
          scp -o StrictHostKeyChecking=no app.tar.gz ubuntu@${{ secrets.SERVER_HOST }}:/home/ubuntu/

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} <<'EOF'
            set -e
            cd /home/dinil-dev/system-storage/apps/${{ env.SERVICE_NAME }}
            sudo systemctl stop ${SERVICE_NAME} || true
            rm -rf *
            tar -xvzf /home/ubuntu/app.tar.gz -C /home/dinil-dev/system-storage/apps/${{ env.SERVICE_NAME }}
            npm ci --omit=dev
            sudo systemctl start ${SERVICE_NAME}
            echo "Deployment complete!"
          EOF
